### ISSUE TITLE
SVG display difference issue

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [hugomods/icons#295]
There are differences between how SVGs are being displayed based on how I display them for some reason. One is low detail (even missing the map's pin dot), one is normal. Both are the same SVG from Taber Icons (it happens with them all though, at least all from Tabler Icons)

See the differences. They should be identical.
<img width="232" alt="screen" src="https://github.com/hugomods/icons/assets/76442625/83351677-89e4-409f-943a-57264da1590d">

Here is how they are displayed.
<img width="407" alt="code" src="https://github.com/hugomods/icons/assets/76442625/4c5f24c0-d98e-4977-b4f7-a895a7a6fe64">

**Comment by razonyang** [comment]
Thanks for reporting this bug.

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
The bug still seems to be present in the latest version (v0.6.2)

![image](https://github.com/hugomods/icons/assets/76442625/92c9e48f-aa41-48a0-9958-fdbff388bdb0)

**Comment by razonyang** [comment]
> The bug still seems to be present in the latest version (v0.6.2)

Does restart Hugo server help (cache issue)?

I've tested on my site.

![image](https://github.com/hugomods/icons/assets/17720932/50633279-595b-4182-88a3-490d562705c1)

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
After testing it in Firefox and Brave with cleared cache, the issue still seems to be present.

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
I should add that I am testing the partial version on a html page.

**Comment by razonyang** [comment]
> I should add that I am testing the partial version on a html page.

That's same, since the shortcode invoke the partial to render icon.

> After testing it in Firefox and Brave with cleared cache, the issue still seems to be present.

Could you please provide a test/public repo to reproduce it?

**Comment by razonyang** [comment]
> After testing it in Firefox and Brave with cleared cache, the issue still seems to be present.

Btw, I'm talking Hugo cache (not browser cache), since we use `partialCached` to parse SVG attributes, restart Hugo server or rebuild the site to see if it work.

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Could you upload a hugo site in a zip archive, and I'll test it on my end?

**Comment by razonyang** [comment]
```sh
git clone --depth 1 https://github.com/hugomods/site.git hugomods-site
cd hugomods-site/main
npm ci
npm run dev
```

Modify the `main\content\docs\icons\index.md` with the `tabler`'s `map-2` icon, and thn open `http://localhost:6060/docs/icons/`.

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
After deleting the hugo_cache I still encounter the problem. I suggest you try using the partial, as when I use the shortcode it works as expected. Using the partial is where I encounter the issue.

**Comment by razonyang** [comment]
They are same, the partial will always to be invoked.

![image](https://github.com/hugomods/icons/assets/17720932/50305052-1b8f-4e89-a0eb-b97aaee5cf0b)

See https://github.com/hugomods/icons/blob/6d133ec85aa05d2910b061a575153e05db96e45d/layouts/shortcodes/icons/icon.html#L15.

Please provide a minimal reproducible repo to check the cause. I didn't see any problem on my two sites...

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Please see this minimal site:
[hugo.zip](https://github.com/hugomods/icons/files/14239501/hugo.zip)

This is what I'm seeing.
![image](https://github.com/hugomods/icons/assets/76442625/28a09ee1-f70d-470f-8556-65807b127e5c)

**Comment by razonyang** [comment]
You're still using the old version, I think you missed my [comment](https://github.com/hugomods/icons/issues/295?notification_referrer_id=NT_kwDOAQ5mZLM5NDIwNjE5OTgxOjE3NzIwOTMy#issuecomment-1938665985) above. 
![image](https://github.com/hugomods/icons/assets/17720932/1ca51dac-4f7d-4337-93aa-87da201d4087)

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Thanks, it was my mistake. Where is Hugo cache kept? I deleted the folder in roaming, but the issue persisted even after that. I ran a clean-up and restarted my pc, only then your fix came into effect.

**Comment by razonyang** [comment]
> I deleted the folder in roaming, but the issue persisted even after that. I ran a clean-up and restarted my pc, only then your fix came into effect.

Not sure, I guess the module won't upgrade automatically, even you clear the hugo mod cache, then old version (go.mod, go.sum) will be downloaded again.
