### ISSUE TITLE
Cannot use any other icon except bootstrap?

### ISSUE THREAD

**Issue by philwinder** [hugomods/icons#376]
I think I'm doing something wrong, but no matter what I try, only bootstrap works.

For example, with:

```
module:
  imports:
  - path: github.com/hugomods/icons/vendors/tabler
```

And on a page somewhere:

```
{{< ico tabler home >}}
```

In the terminal I get:

```
WARN  [icons] tabler's home doesn't exist.
```

I've tried various other providers and names of things. But bootstrap is the only one that works. 

Any ideas?

**Comment by razonyang** [comment]
Tha't because Tabler icons are separated into multiple folders (categories), you can use the following instead.

```
{{< ico "tabler/filled" "home" >}}
```

You can find and filter icons [here](https://icons.hugomods.com/#search).

**Comment by razonyang** [comment]
Closed as per above comment.
